const { pessoa, veiculo } = require('gerador');

class PersonService {
    static generatePersons(quantity = 0) {
        console.log(`Gerando ${quantity} pessoa${quantity == 1 ? '' : 's'}`);
        let persons = [];

        for (let index = 0; index < quantity; index++) {
            const person = [
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa(),
                pessoa.nome(),
                pessoa.estadoCivil(),
                pessoa.nomeFeminino(),
                pessoa.nomeMasculino(),
                pessoa.sexo(),
                veiculo.placa()
            ]

            persons.push(person);
        }

        console.log(`Gerou ${quantity} pessoa${quantity == 1 ? '' : 's'}`);


        return {
            columns: [
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA",
                "NOME",
                "ESTADO CIVIL",
                "MÃE",
                "PAI",
                "SEXO",
                "PLACA"
            ],
            tab: "Pessoas",
            rows: persons
        };
    }
}

module.exports = PersonService;
